services:
  obt-tbot:
    # build: .  # Собираем образ из текущей директории
    image: yca4/obt-telegram-bot-image:latest
    container_name: telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
